/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

public class Library {
    public static int[] roll(int num){
        int[] resultsArr = new int[num];
        for(int i = 0; i<num; i++){
            int val = (int)Math.floor(Math.random() * 7);
            resultsArr[i] = val;
        }
        return resultsArr;
    }

    public static boolean containsDuplicates(int[] arr){
        for(int i = 0; i<arr.length; i++){
            for(int j = 0; j < arr.length; j++){
                if(i != j) {
                    if (arr[i] == arr[j]) {
                        return true;
                    }
                }
            }
        }
        return false;
    }

    public static double average(int[] arr){
        int total = 0;

        for(int i =0; i<arr.length;i++){
            total += arr[i];
        }

        return (double)total/arr.length;
    }

    public static int[] lowestArrayAverage(int[][] arr){
        int lowestIndex = 0;
        double lowestAverage = Double.POSITIVE_INFINITY;;

        for(int i = 0; i < arr.length; i++){
            if(average(arr[i])<lowestAverage){
                lowestAverage = average(arr[i]);
                lowestIndex = i;
            }
        }
        return arr[lowestIndex];
    }

}
