/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testLinterManyErrors() {
        App.linter("./src/main/resources/gates.js");

    }
    @Test public void testLinterNoErrors() {
        App.linter("./src/test/resources/testLinter.js");

    }
    @Test public void testLinterEmptyFile() {
        App.linter("./src/test/resources/testLinterEmpty.js");

    }
    @Test public void testLinterFewErrors() {
        App.linter("./src/test/resources/testLinterFewErrors.js");

    }
    @Test public void testLinterOneError() {
        App.linter("./src/test/resources/testLinterOneError.js");

    }
}
