/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("hi");
        linter("./src/main/resources/gates.js");
    }

    public static void linter(String path){
        Scanner s = null;
        int lineCount = 0;

        try{
            s = new Scanner(new BufferedReader(new FileReader(path)));
            while(s.hasNextLine()){
                lineCount++;
                String line = s.nextLine();

                if((!line.contains(";")) && (line.length()>0) &&(!line.contains("if")) && (!line.contains("else")) && (line.charAt(line.length()-1)!= '{') && (line.charAt(line.length()-1)!= '}')){

                    System.out.println("Line " + lineCount + " does not contain a semicolon.");
                }
            }

        }catch (FileNotFoundException e){
            System.out.println("File not found");

        }
    }

}
