/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Assert;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class LibraryTest {


    @Test public void testRoll() {

        assertTrue("someLibraryMethod should return 'true'", Library.roll(5).length == 5);
    }

    @Test public void testContainsDuplicates(){
        int[] trueArray = {1,2,3,3};

        assertTrue(Library.containsDuplicates(trueArray));

    }
    @Test public void testContainsDuplicates_false(){

        int[] falseArray = {1,2,3,4};

        assertTrue(!Library.containsDuplicates(falseArray));
    }

    @Test public void testAverage(){

        int[] trueArray = {2,2,2,2};
        int[] trueArrayAgain = {2,4};
        assertTrue(Library.average(trueArray)==2.00);
        assertTrue(Library.average(trueArrayAgain)==3);
    }
    @Test public void testAverage_false(){

        int[] falseArray = {2,2,2,8};
        int[] falseArrayAgain = {2,5};
        assertTrue(Library.average(falseArray)!=2.00);
        assertTrue(Library.average(falseArrayAgain)!=3);
    }

    @Test public void testLowestArrayAverage(){
        int[][] arrayOfArrays = {
                {10, 10, 10},
                {57, 65, 65},
                {5, 5, 6},
                {65, 56, 55}
        };

        int[] lowestArray = {5,5,6};

        assertArrayEquals(lowestArray,Library.lowestArrayAverage(arrayOfArrays));

    }


}
