/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritence;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

import static org.junit.Assert.*;

@RunWith(Suite.class)
@Suite.SuiteClasses({RestaurantTest.class,ReviewTest.class,ShopTest.class,TheaterTest.class})
public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
////        Library classUnderTest = new Library();
////        assertTrue(true);
//    }
}
